id: upload_configure_qlik
learningObjectives:
  - Upload the demo Qlik Sense app and configure sharing permissions
hints:
  - The app ID looks like a GUID: 946d5af4-e089-42d3-9ba7-1d21adb68472
  - Can't find the app ID? Open the app and check the URL - it's right there!
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: "Time to set up our demo app in Qlik Cloud! First, log into your tenant."
          - text: "Look for the 'Add new' or '+' button at the top - that's where you'll upload your demo Qlik Sense app. You'll find the app in your project files."
          - text: "Once your app is uploaded, open it up. Take a look at the URL in your browser - you'll see an important ID there that looks like this: `946d5af4-e089-42d3-9ba7-1d21adb68472`. This is your app ID!"
          - text: "Next, let's give everyone access to your app. Find the 'Spaces' section in the left menu and create a new shared space. Move your app there by clicking the '⋮' menu on your app and selecting 'Move'."
          - text: "Last thing - in your new space's settings, make sure to grant 'Can view' access to everyone in the tenant."
          - text: "Now, share that app ID with me and we'll move forward!"
trigger: 
  type: user_message
  params:
    person: lucca
  flowNode:
    if:
      conditions:
        - conditionId: text_match_regex
          params:
            regex: .*([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}).*
      then:
        do:
        - actionId: bot_message
          params:
            person: lucca
            messages:
            - text: "Perfect! That's a valid app ID. Now we can move on to setting up our environment variables!"
        - actionId: finish_step
      else:
        do:
        - actionId: bot_message
          params:
            person: lucca
            messages:
            - text: "Hmm, that doesn't look like a valid app ID. It should be a GUID that looks like this: 946d5af4-e089-42d3-9ba7-1d21adb68472. Could you check and try again?"

