id: install_run_app
learningObjectives:
  - Install dependencies and run the app locally.
hints:
  - Need help? Check the [Qlik Embed Documentation](https://qlik.dev/libraries-and-tools/qlik-embed)
    for the setup scoop.
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: "Almost there! Time to plug in the dependencies and breathe life into your
              app. Let's transform static code into a dynamic experience."
          - text: "Run `npm install` to gather all dependencies—this command's the ship
              bringing our materials home."
          - text: "Start the server using `npm run dev`. Once it's running, click the 'Open in Browser' button
              that appears in your Codespace to see your masterpiece!"
    - actionId: ready_message
      params:
        person: lucca
trigger:
  type: user_ready_response
  flowNode:
    do:
      - actionId: bot_message
        params:
          person: lucca
          messages:
            - text: Tada! You've successfully woven Qlik Sense into the magic fabric that is
                our app. Ness will be thrilled—this sort of wizardry is what
                keeps us at the forefront of data analysis. Thank you for making
                this happen! Until next time...
      - actionId: finish_step
